using Newtonsoft.Json;
using System;
using System.Collections.ObjectModel;
using System.Net.Http;
using System.Net.NetworkInformation;
using WeCode_Next.DataModel;
using Windows.ApplicationModel.DataTransfer;
using Windows.Foundation;
using Windows.Storage;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

namespace WeCode_Next.Pages
{
    public sealed partial class BuildFeed : Page
    {
        private DataTransferManager dataTransferManager;
        private string Info;

        public BuildFeed()
        {
            this.InitializeComponent();
            ApplicationDataContainer _appSettings = ApplicationData.Current.LocalSettings;
            if (_appSettings.Values.ContainsKey("OfflineMode"))
            {
                if (Convert.ToBoolean(_appSettings.Values["OfflineMode"]))
                {
                    NC.Visibility = Windows.UI.Xaml.Visibility.Visible;
                    bf.Visibility = Windows.UI.Xaml.Visibility.Collapsed;
                    NC.Text = "Currently in Offline Mode. ";
                }
                else
                {
                    if (NetworkInterface.GetIsNetworkAvailable())
                    {
                        NC.Visibility = Windows.UI.Xaml.Visibility.Collapsed;
                        bf.Visibility = Windows.UI.Xaml.Visibility.Visible;
                        NewsLoad();
                    }
                    else
                    {
                        NC.Visibility = Windows.UI.Xaml.Visibility.Visible;
                        bf.Visibility = Windows.UI.Xaml.Visibility.Collapsed;
                    }
                }
            }
            else
            {
                if (NetworkInterface.GetIsNetworkAvailable())
                {
                    NC.Visibility = Windows.UI.Xaml.Visibility.Collapsed;
                    bf.Visibility = Windows.UI.Xaml.Visibility.Visible;
                    NewsLoad();
                }
                else
                {
                    NC.Visibility = Windows.UI.Xaml.Visibility.Visible;
                    bf.Visibility = Windows.UI.Xaml.Visibility.Collapsed;
                }
            }
        }
        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            // Register the current page as a share source.
            this.dataTransferManager = DataTransferManager.GetForCurrentView();
            this.dataTransferManager.DataRequested += DataTransferManager_DataRequested;
        }
        private async void NewsLoad()
        {
            try
            {
                //string uri = "https://buildfeed.net/api/GetBuildsByLab?lab=rs_prerelease";
                string uri = "https://buildfeed.net/api/";
                var client = new HttpClient();
                HttpResponseMessage response = await client.GetAsync(new Uri(uri));
                ObservableCollection<BuildFeedItem> Data = JsonConvert.DeserializeObject<ObservableCollection<BuildFeedItem>>(await response.Content.ReadAsStringAsync());
                bf.ItemsSource = Data;
            }
            catch (Exception e)
            {
            }
        }

        private void DataTransferManager_DataRequested(DataTransferManager sender, DataRequestedEventArgs args)
        {
            DataRequest request = args.Request;
            request.Data.SetText(Info);
            request.Data.Properties.Title = "UWP DevKit";
            request.Data.Properties.Description = "Build Information Shared From BuildFeed Feature";
        }

        private void Share_Click(object sender, RoutedEventArgs e)
        {
            var item = (sender as FrameworkElement).DataContext;
            BuildFeedItem data = item as BuildFeedItem;
            Info = data.MajorVersion + "." + data.MinorVersion + "." + data.Number + "." + data.Revision + "\r"
                + "Source Type: " + data.SourceType + "\r"
                + "Build Date:" + data.BuildTime + "\r"
                + "Full Build Name: " + data.FullBuildString + "\r"
                + "Data Generated By UWP DevKit, Source From BuildFeed";
            DataTransferManager.ShowShareUI();
        }
    }
}
